# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eScaner' do

pod 'PDFGenerator', '~> 3.1'
pod 'PDFReader'
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!


  # Pods for eScaner

end
